spring:
  application:
    name: "ResumeHong"

  #Auto Restart Configuration
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

  # DB Connection Configuration  - to the server
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/resume
    username: resume
    password: 1234

  #JPA Configuration
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy

    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  # Spring Security Default Account
  security:
    user:
      name: test
      password: 1234

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace